In [ ]:
!pip install fbprophet

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("data/acled_social_iso3.csv")

In [7]:
df.head()

,Unnamed: 0,Unnamed: 0.1,EVENT_DATE_MONTH,COUNTRY,Battles,Explosions/Remote violence,Protests,Riots,Strategic developments,Violence against civilians,FATALITIES,YEAR,"Life expectancy at birth, total (years)",GDP (current US$),"Death rate, crude (per 1,000 people)",Population growth (annual %),Urban population (% of total),"Central government, Fiscal Balance (Current US $)","Population, Total",iso3
0,0,0,1997-01,Algeria,8.0,11.0,0.0,0.0,0.0,23.0,465,1997,68.932,4.817786e+10,5.400,1.617981,58.425744,1.457813e+09,29887717.0,DZA
1,1,1,1997-01,Angola,0.0,0.0,0.0,0.0,1.0,3.0,40,1997,43.088,7.074393e+09,21.350,2.808642,28.051572,-1.616077e+09,13801868.0,AGO
2,2,2,1997-01,Burundi,9.0,0.0,0.0,0.0,2.0,8.0,796,1997,50.176,1.194241e+09,15.428,1.373382,7.558006,-6.224048e+07,6420397.0,BDI
3,3,3,1997-01,Central African Republic,6.0,0.0,0.0,0.0,0.0,1.0,14,1997,45.867,9.445119e+08,18.364,2.362984,36.611405,1.620297e+07,3497910.0,CAF
4,4,4,1997-01,Democratic Republic of Congo,16.0,1.0,0.0,0.0,0.0,3.0,992,1997,0.000,0.000000e+00,0.000,0.000000,0.000000,0.000000e+00,0.0,COD

In [14]:
df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'], inplace=True)

In [17]:
df[df["COUNTRY"] == "Algeria"].corr().columns

Index(['Battles', 'Explosions/Remote violence', 'Protests', 'Riots',
       'Strategic developments', 'Violence against civilians', 'FATALITIES',
       'YEAR', 'Life expectancy at birth, total (years)', 'GDP (current US$)',
       'Death rate, crude (per 1,000 people)', 'Population growth (annual %)',
       'Urban population (% of total)',
       'Central government, Fiscal Balance (Current US $)',
       'Population, Total'],
      dtype='object')

In [18]:
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

In [20]:
df_acled = df

In [22]:
corr = df_acled[df_acled['COUNTRY'] == 'Algeria'].corr()
coordinates = corr.values.tolist()
columns = list(corr.columns)
    
trace1 = {
        "type": "heatmap", 
        "x": columns, 
        "y": columns, 
        "z": coordinates
        }
data = trace1
layout = {"title": "Features Correlation Matrix"}
fig = dict(data=data, layout=layout)
plot(fig)

'temp-plot.html'

In [23]:
pred_df = pd.read_csv("data/results_xgb_classifier_hackathon_labels.csv")

In [24]:
pred_df

    Unnamed: 0 iso3  battle_case  protest_riots_case
0          255  DZA          0.0                 1.0
1          374  AGO          0.0                 1.0
2          614  BDI          0.0                 1.0
3          809  CAF          1.0                 0.0
4         1074  COD          1.0                 1.0
5         1242  EGY          0.0                 1.0
6         1475  ETH          0.0                 1.0
7         1623  CIV          0.0                 1.0
8         1886  KEN          0.0                 1.0
9         2063  LBY          1.0                 1.0
10        2206  MLI          1.0                 1.0
11        2396  NER          1.0                 1.0
12        2667  NGA          0.0                 1.0
13        2809  RWA          0.0                 0.0
14        2845  SLE          0.0                 1.0
15        3061  ZAF          0.0                 1.0
16        3332  SDN          0.0                 1.0
17        3358  TGO          0.0                 0.0
18        3601  UGA          0.0                 1.0
19        3683  BFA          1.0                 1.0
20        3806  CMR          1.0                 1.0
21        3943  TCD          0.0                 1.0
22        4023  LSO          0.0                 0.0
23        4259  SOM          1.0                 1.0
24        4370  GHA          0.0                 1.0
25        4576  ZMB          0.0                 0.0
26        4660  MWI          0.0                 1.0
27        4794  ZWE          0.0                 1.0
28        4884  MOZ          0.0                 1.0
29        4906  GMB          0.0                 0.0
30        5026  TZA          0.0                 0.0
31        5150  MDG          0.0                 1.0
32        5159  GAB          0.0                 0.0
33        5203  BEN          0.0                 0.0
34        5207  BWA          0.0                 0.0
35        5309  GIN          0.0                 1.0
36        5407  TUN          0.0                 1.0
37        5505  SSD          1.0                 1.0

In [48]:
df_time = df[["EVENT_DATE_MONTH", "Battles"]]

In [49]:
df_time["EVENT_DATE_MONTH"] = pd.to_datetime(df_time["EVENT_DATE_MONTH"])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [31]:
df["Violence against civilians"].value_counts()

0.0      3151
1.0      1682
2.0       756
3.0       527
4.0       337
         ...
85.0        1
93.0        1
76.0        1
98.0        1
127.0       1
Name: Violence against civilians, Length: 98, dtype: int64

In [30]:
df.head()

,EVENT_DATE_MONTH,COUNTRY,Battles,Explosions/Remote violence,Protests,Riots,Strategic developments,Violence against civilians,FATALITIES,YEAR,"Life expectancy at birth, total (years)",GDP (current US$),"Death rate, crude (per 1,000 people)",Population growth (annual %),Urban population (% of total),"Central government, Fiscal Balance (Current US $)","Population, Total",iso3
0,1997-01,Algeria,8.0,11.0,0.0,0.0,0.0,23.0,465,1997,68.932,4.817786e+10,5.400,1.617981,58.425744,1.457813e+09,29887717.0,DZA
1,1997-01,Angola,0.0,0.0,0.0,0.0,1.0,3.0,40,1997,43.088,7.074393e+09,21.350,2.808642,28.051572,-1.616077e+09,13801868.0,AGO
2,1997-01,Burundi,9.0,0.0,0.0,0.0,2.0,8.0,796,1997,50.176,1.194241e+09,15.428,1.373382,7.558006,-6.224048e+07,6420397.0,BDI
3,1997-01,Central African Republic,6.0,0.0,0.0,0.0,0.0,1.0,14,1997,45.867,9.445119e+08,18.364,2.362984,36.611405,1.620297e+07,3497910.0,CAF
4,1997-01,Democratic Republic of Congo,16.0,1.0,0.0,0.0,0.0,3.0,992,1997,0.000,0.000000e+00,0.000,0.000000,0.000000,0.000000e+00,0.0,COD

In [50]:
def fatalities(row):
    if row["FATALITIES"] > 50:
        return 1
    else:
        return 0
    
def violence_explosion(row):
    if row["Explosions/Remote violence"] > 10:
        return 1
    else:
        return 0

def protests(row):
    if row["Protests"] > 10:
        return 1
    else:
        return 0
    
def violence_civilians(row):
    if row["Violence against civilians"] > 10:
        return 1
    else:
        return 0

In [51]:
df_time["fat_reg"] = df.apply(fatalities, axis=1)
df_time["exp_reg"] = df.apply(violence_explosion, axis=1)
df_time["pro_reg"] = df.apply(protests, axis=1)
df_time["civ_reg"] = df.apply(violence_civilians, axis=1)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [52]:
from fbprophet import Prophet

In [54]:
df_time

     EVENT_DATE_MONTH  Battles  fat_reg  exp_reg  pro_reg  civ_reg
0          1997-01-01      8.0        1        1        0        1
1          1997-01-01      0.0        0        0        0        0
2          1997-01-01      9.0        1        0        0        0
3          1997-01-01      6.0        0        0        0        0
4          1997-01-01     16.0        1        0        0        0
...               ...      ...      ...      ...      ...      ...
8768       2020-02-01      0.0        0        0        0        0
8769       2020-02-01      0.0        0        0        1        0
8770       2020-02-01      2.0        0        0        0        0
8771       2020-02-01      0.0        0        0        0        0
8772       2020-02-01      0.0        0        0        0        0

[8773 rows x 6 columns]

In [56]:
df_time.rename(columns={"EVENT_DATE_MONTH":"ds", "Battles":"y"}, inplace=True)

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:4130: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [69]:
m = Prophet(daily_seasonality=True, weekly_seasonality=True)
m.add_regressor('fat_reg')
m.add_regressor('exp_reg')
m.add_regressor('pro_reg')
m.add_regressor('civ_reg')

m.fit(df_time, )
future = m.make_future_dataframe(periods=df_time.shape[0])

future["fat_reg"] = df.apply(fatalities, axis=1)
future["exp_reg"] = df.apply(violence_explosion, axis=1)
future["pro_reg"] = df.apply(protests, axis=1)
future["civ_reg"] = df.apply(violence_civilians, axis=1)

forecast = m.predict(future)
m.plot_components(forecast)

ValueError: Found NaN in column 'fat_reg'