In [2]:
import pandas as pd

In [3]:
df_social = pd.read_csv("social_data.csv")

In [4]:
df_social['year'] = pd.to_datetime(df_social['Date']).dt.year

In [5]:
df_social

,Unnamed: 0,CountryName,Country,IndicatorName,Units,Scale,Frequency,Date,Value,year
0,52084,Cameroon,CMR,"Central government, Fiscal Balance (Current US $)",current US$,1,A,1997-01-01,-3.233041e+08,1997
1,52085,Cameroon,CMR,"Central government, Fiscal Balance (Current US $)",current US$,1,A,1998-01-01,-3.604077e+08,1998
2,52086,Cameroon,CMR,"Central government, Fiscal Balance (Current US $)",current US$,1,A,1999-01-01,-2.971021e+08,1999
3,52087,Cameroon,CMR,"Central government, Fiscal Balance (Current US $)",current US$,1,A,2000-01-01,4.082743e+08,2000
4,52088,Cameroon,CMR,"Central government, Fiscal Balance (Current US $)",current US$,1,A,2001-01-01,1.242385e+08,2001
...,...,...,...,...,...,...,...,...,...,...
7388,1660492,Togo,TGO,Urban population (% of total),% of total,1,A,2016-01-01,3.966628e+01,2016
7389,1660493,Togo,TGO,Urban population (% of total),% of total,1,A,2017-01-01,4.009672e+01,2017
7390,1660494,Togo,TGO,Urban population (% of total),% of total,1,A,2018-01-01,4.052414e+01,2018
7391,1660495,Togo,TGO,Urban population (% of total),% of total,1,A,2019-01-01,4.094997e+01,2019
7392,1660496,Togo,TGO,Urban population (% of total),% of total,1,A,2020-01-01,4.137520e+01,2020

In [44]:
df_acled = pd.read_csv('acled_africa_month_comp.csv')

In [45]:
df_acled

,Unnamed: 0,EVENT_DATE_MONTH,COUNTRY,Battles,Explosions/Remote violence,Protests,Riots,Strategic developments,Violence against civilians,FATALITIES,YEAR
0,0,1997-01,Algeria,8.0,11.0,0.0,0.0,0.0,23.0,465,1997
1,1,1997-01,Angola,0.0,0.0,0.0,0.0,1.0,3.0,40,1997
2,2,1997-01,Burundi,9.0,0.0,0.0,0.0,2.0,8.0,796,1997
3,3,1997-01,Central African Republic,6.0,0.0,0.0,0.0,0.0,1.0,14,1997
4,4,1997-01,Democratic Republic of Congo,16.0,1.0,0.0,0.0,0.0,3.0,992,1997
...,...,...,...,...,...,...,...,...,...,...,...
8768,8768,2020-02,Sudan,0.0,0.0,4.0,4.0,0.0,0.0,0,2020
8769,8769,2020-02,Tunisia,0.0,0.0,25.0,0.0,0.0,0.0,0,2020
8770,8770,2020-02,Uganda,2.0,0.0,2.0,2.0,0.0,3.0,3,2020
8771,8771,2020-02,Zambia,0.0,0.0,0.0,3.0,0.0,0.0,2,2020
8772,8772,2020-02,Zimbabwe,0.0,0.0,0.0,0.0,1.0,0.0,0,2020

In [11]:
rel_cat = ["Life expectancy at birth, total (years)",
           "GDP (current US$)",
           "Death rate, crude (per 1,000 people)",
           "Population growth (annual %)",
           "Urban population (% of total)",
           "Central government, Fiscal Balance (Current US $)",
           "Population, Total"
          ]

In [19]:
cat_short = ["life_exp",
           "gdp",
           "death_rate",
           "pop_growth",
           "urb_pop",
           "gov_fin",
           "pop_total"
          ]

In [46]:
for cou in df_acled.COUNTRY.unique():
    for year in df_acled.YEAR.unique():
        for cat in rel_cat:
            try:
                value = df_social[(df_social["IndicatorName"] == cat) & (df_social["CountryName"] == cou) & (df_social['year'] == year)]['Value'].values[0]
            except:
                value=0
            indexes = df_acled[(df_acled["YEAR"] == year) & (df_acled["COUNTRY"] == cou)].index
            df_acled.loc[indexes, cat] = value

In [48]:
df_acled.drop(columns=['Unnamed: 0'], inplace=True)

In [49]:
df_acled.to_csv('acled_social.csv')